name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'  # Chạy 6 tiếng một lần
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: tgymnich/fork-sync@v1.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Sửa từ github_token thành token
          owner: E-Commerce-O  # Thay bằng tên chủ sở hữu repo gốc
          base: main  # Nhánh của repo gốc
          head: main  # Nhánh của fork của bạn