name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'  # Chạy 6 tiếng một lần
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: tgymnich/fork-sync@v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: hai000       # Tên người sở hữu repository gốc
          base: main                  # Nhánh chính của repository gốc (thường là main hoặc master)
          head: main                  # Nhánh của fork mà bạn muốn cập nhật